spring:
  datasource:
    url: "jdbc:mysql://Localhost:3306/baby"
    username: root
    password: huy123456
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nhathuy2903@gmail.com
    password: bwqbezxsdofjnvwq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
jwt: 
  signerKey: "AMw7awxveLn+4FOcpEhfHO2kSFjpx250KqHX0Ru9hdETJa5OiPcf8fS4lJ+UcegBsTFJhvMf0fkV"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
  